# Generated by Django 5.2.7 on 2025-10-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0033_speakerprofile_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speakerprofile",
            old_name="organization",
            new_name="affiliation",
        ),
    ]
